export const data = [
  {
    tableno: "20A",
    OrderID: "#102977",
    CustomerName: "Rahul",
    ItemStatus: "New x 2 , Cooking x 1 , Ready to serve x 2 , Served 1",
    PaymentStatus: "In Progress",
    PaymentAction: "Done",
  },
  {
    tableno: "20A",
    OrderID: "#102977",
    CustomerName: "Rahul",
    ItemStatus: "New x 2 , Cooking x 1 , Ready to serve x 2 , Served 1",
    PaymentStatus: "In Progress",
    PaymentAction: "Done",
  },
  {
    tableno: "20A",
    OrderID: "#102977",
    CustomerName: "Rahul",
    ItemStatus: "New x 2 , Cooking x 1 , Ready to serve x 2 , Served 1",
    PaymentStatus: "In Progress",
    PaymentAction: "Done",
  },
  {
    tableno: "20A",
    OrderID: "#102977",
    CustomerName: "Rahul",
    ItemStatus: "New x 2 , Cooking x 1 , Ready to serve x 2 , Served 1",
    PaymentStatus: "In Progress",
    PaymentAction: "Done",
  },
  {
    tableno: "20A",
    OrderID: "#102977",
    CustomerName: "Rahul",
    ItemStatus: "New x 2 , Cooking x 1 , Ready to serve x 2 , Served 1",
    PaymentStatus: "In Progress",
    PaymentAction: "Done",
  },
  {
    tableno: "20A",
    OrderID: "#102977",
    CustomerName: "Rahul",
    ItemStatus: "New x 2 , Cooking x 1 , Ready to serve x 2 , Served 1",
    PaymentStatus: "In Progress",
    PaymentAction: "Done",
  },
  {
    tableno: "20A",
    OrderID: "#102977",
    CustomerName: "Rahul",
    ItemStatus: "New x 2 , Cooking x 1 , Ready to serve x 2 , Served 1",
    PaymentStatus: "In Progress",
    PaymentAction: "Done",
  },
  {
    tableno: "20A",
    OrderID: "#102977",
    CustomerName: "Rahul",
    ItemStatus: "New x 2 , Cooking x 1 , Ready to serve x 2 , Served 1",
    PaymentStatus: "In Progress",
    PaymentAction: "Done",
  },
  {
    tableno: "20A",
    OrderID: "#102977",
    CustomerName: "Rahul",
    ItemStatus: "New x 2 , Cooking x 1 , Ready to serve x 2 , Served 1",
    PaymentStatus: "In Progress",
    PaymentAction: "Done",
  },
  {
    tableno: "20A",
    OrderID: "#102977",
    CustomerName: "Rahul",
    ItemStatus: "New x 2 , Cooking x 1 , Ready to serve x 2 , Served 1",
    PaymentStatus: "In Progress",
    PaymentAction: "Done",
  },
  {
    tableno: "20A",
    OrderID: "#102977",
    CustomerName: "Rahul",
    ItemStatus: "New x 2 , Cooking x 1 , Ready to serve x 2 , Served 1",
    PaymentStatus: "In Progress",
    PaymentAction: "Done",
  },
  {
    tableno: "20A",
    OrderID: "#102977",
    CustomerName: "Rahul",
    ItemStatus: "New x 2 , Cooking x 1 , Ready to serve x 2 , Served 1",
    PaymentStatus: "In Progress",
    PaymentAction: "Done",
  },
  {
    tableno: "20A",
    OrderID: "#102977",
    CustomerName: "Rahul",
    ItemStatus: "New x 2 , Cooking x 1 , Ready to serve x 2 , Served 1",
    PaymentStatus: "In Progress",
    PaymentAction: "Done",
  },
  {
    tableno: "20A",
    OrderID: "#102977",
    CustomerName: "Rahul",
    ItemStatus: "New x 2 , Cooking x 1 , Ready to serve x 2 , Served 1",
    PaymentStatus: "In Progress",
    PaymentAction: "Done",
  },
  {
    tableno: "20A",
    OrderID: "#102977",
    CustomerName: "Rahul",
    ItemStatus: "New x 2 , Cooking x 1 , Ready to serve x 2 , Served 1",
    PaymentStatus: "In Progress",
    PaymentAction: "Done",
  },
  {
    tableno: "20A",
    OrderID: "#102977",
    CustomerName: "Rahul",
    ItemStatus: "New x 2 , Cooking x 1 , Ready to serve x 2 , Served 1",
    PaymentStatus: "In Progress",
    PaymentAction: "Done",
  },
  {
    tableno: "20A",
    OrderID: "#102977",
    CustomerName: "Rahul",
    ItemStatus: "New x 2 , Cooking x 1 , Ready to serve x 2 , Served 1",
    PaymentStatus: "In Progress",
    PaymentAction: "Done",
  },
  {
    tableno: "20A",
    OrderID: "#102977",
    CustomerName: "Rahul",
    ItemStatus: "New x 2 , Cooking x 1 , Ready to serve x 2 , Served 1",
    PaymentStatus: "In Progress",
    PaymentAction: "Done",
  },
  {
    tableno: "20A",
    OrderID: "#102977",
    CustomerName: "Rahul",
    ItemStatus: "New x 2 , Cooking x 1 , Ready to serve x 2 , Served 1",
    PaymentStatus: "In Progress",
    PaymentAction: "Done",
  },
  {
    tableno: "20A",
    OrderID: "#102977",
    CustomerName: "Rahul",
    ItemStatus: "New x 2 , Cooking x 1 , Ready to serve x 2 , Served 1",
    PaymentStatus: "In Progress",
    PaymentAction: "Done",
  },
  {
    tableno: "20A",
    OrderID: "#102977",
    CustomerName: "Rahul",
    ItemStatus: "New x 2 , Cooking x 1 , Ready to serve x 2 , Served 1",
    PaymentStatus: "In Progress",
    PaymentAction: "Done",
  },
  {
    tableno: "20A",
    OrderID: "#102977",
    CustomerName: "Rahul",
    ItemStatus: "New x 2 , Cooking x 1 , Ready to serve x 2 , Served 1",
    PaymentStatus: "In Progress",
    PaymentAction: "Done",
  },
  {
    tableno: "20A",
    OrderID: "#102977",
    CustomerName: "Rahul",
    ItemStatus: "New x 2 , Cooking x 1 , Ready to serve x 2 , Served 1",
    PaymentStatus: "In Progress",
    PaymentAction: "Done",
  },
  {
    tableno: "20A",
    OrderID: "#102977",
    CustomerName: "Rahul",
    ItemStatus: "New x 2 , Cooking x 1 , Ready to serve x 2 , Served 1",
    PaymentStatus: "In Progress",
    PaymentAction: "Done",
  },
  {
    tableno: "20A",
    OrderID: "#102977",
    CustomerName: "Rahul",
    ItemStatus: "New x 2 , Cooking x 1 , Ready to serve x 2 , Served 1",
    PaymentStatus: "In Progress",
    PaymentAction: "Done",
  },
  {
    tableno: "20A",
    OrderID: "#102977",
    CustomerName: "Rahul",
    ItemStatus: "New x 2 , Cooking x 1 , Ready to serve x 2 , Served 1",
    PaymentStatus: "In Progress",
    PaymentAction: "Done",
  },
  {
    tableno: "20A",
    OrderID: "#102977",
    CustomerName: "Rahul",
    ItemStatus: "New x 2 , Cooking x 1 , Ready to serve x 2 , Served 1",
    PaymentStatus: "In Progress",
    PaymentAction: "Done",
  },
  {
    tableno: "20A",
    OrderID: "#102977",
    CustomerName: "Rahul",
    ItemStatus: "New x 2 , Cooking x 1 , Ready to serve x 2 , Served 1",
    PaymentStatus: "In Progress",
    PaymentAction: "Done",
  },
  {
    tableno: "20A",
    OrderID: "#102977",
    CustomerName: "Rahul",
    ItemStatus: "New x 2 , Cooking x 1 , Ready to serve x 2 , Served 1",
    PaymentStatus: "In Progress",
    PaymentAction: "Done",
  },
  {
    tableno: "20A",
    OrderID: "#102977",
    CustomerName: "Rahul",
    ItemStatus: "New x 2 , Cooking x 1 , Ready to serve x 2 , Served 1",
    PaymentStatus: "In Progress",
    PaymentAction: "Done",
  },
  {
    tableno: "20A",
    OrderID: "#102977",
    CustomerName: "Rahul",
    ItemStatus: "New x 2 , Cooking x 1 , Ready to serve x 2 , Served 1",
    PaymentStatus: "In Progress",
    PaymentAction: "Done",
  },
  {
    tableno: "20A",
    OrderID: "#102977",
    CustomerName: "Rahul",
    ItemStatus: "New x 2 , Cooking x 1 , Ready to serve x 2 , Served 1",
    PaymentStatus: "In Progress",
    PaymentAction: "Done",
  },
  {
    tableno: "20A",
    OrderID: "#102977",
    CustomerName: "Rahul",
    ItemStatus: "New x 2 , Cooking x 1 , Ready to serve x 2 , Served 1",
    PaymentStatus: "In Progress",
    PaymentAction: "Done",
  },
  {
    tableno: "20A",
    OrderID: "#102977",
    CustomerName: "Rahul",
    ItemStatus: "New x 2 , Cooking x 1 , Ready to serve x 2 , Served 1",
    PaymentStatus: "In Progress",
    PaymentAction: "Done",
  },
  {
    tableno: "20A",
    OrderID: "#102977",
    CustomerName: "Rahul",
    ItemStatus: "New x 2 , Cooking x 1 , Ready to serve x 2 , Served 1",
    PaymentStatus: "In Progress",
    PaymentAction: "Done",
  },
  {
    tableno: "20A",
    OrderID: "#102977",
    CustomerName: "Rahul",
    ItemStatus: "New x 2 , Cooking x 1 , Ready to serve x 2 , Served 1",
    PaymentStatus: "In Progress",
    PaymentAction: "Done",
  },
  {
    tableno: "20A",
    OrderID: "#102977",
    CustomerName: "Rahul",
    ItemStatus: "New x 2 , Cooking x 1 , Ready to serve x 2 , Served 1",
    PaymentStatus: "In Progress",
    PaymentAction: "Done",
  },
  {
    tableno: "20A",
    OrderID: "#102977",
    CustomerName: "Rahul",
    ItemStatus: "New x 2 , Cooking x 1 , Ready to serve x 2 , Served 1",
    PaymentStatus: "In Progress",
    PaymentAction: "Done",
  },
  {
    tableno: "20A",
    OrderID: "#102977",
    CustomerName: "Rahul",
    ItemStatus: "New x 2 , Cooking x 1 , Ready to serve x 2 , Served 1",
    PaymentStatus: "In Progress",
    PaymentAction: "Done",
  },
  {
    tableno: "20A",
    OrderID: "#102977",
    CustomerName: "Rahul",
    ItemStatus: "New x 2 , Cooking x 1 , Ready to serve x 2 , Served 1",
    PaymentStatus: "In Progress",
    PaymentAction: "Done",
  },
  {
    tableno: "20A",
    OrderID: "#102977",
    CustomerName: "Rahul",
    ItemStatus: "New x 2 , Cooking x 1 , Ready to serve x 2 , Served 1",
    PaymentStatus: "In Progress",
    PaymentAction: "Done",
  },
  {
    tableno: "20A",
    OrderID: "#102977",
    CustomerName: "Rahul",
    ItemStatus: "New x 2 , Cooking x 1 , Ready to serve x 2 , Served 1",
    PaymentStatus: "In Progress",
    PaymentAction: "Done",
  },
  {
    tableno: "20A",
    OrderID: "#102977",
    CustomerName: "Rahul",
    ItemStatus: "New x 2 , Cooking x 1 , Ready to serve x 2 , Served 1",
    PaymentStatus: "In Progress",
    PaymentAction: "Done",
  },
  {
    tableno: "20A",
    OrderID: "#102977",
    CustomerName: "Rahul",
    ItemStatus: "New x 2 , Cooking x 1 , Ready to serve x 2 , Served 1",
    PaymentStatus: "In Progress",
    PaymentAction: "Done",
  },
  {
    tableno: "20A",
    OrderID: "#102977",
    CustomerName: "Rahul",
    ItemStatus: "New x 2 , Cooking x 1 , Ready to serve x 2 , Served 1",
    PaymentStatus: "In Progress",
    PaymentAction: "Done",
  },
  {
    tableno: "20A",
    OrderID: "#102977",
    CustomerName: "Rahul",
    ItemStatus: "New x 2 , Cooking x 1 , Ready to serve x 2 , Served 1",
    PaymentStatus: "In Progress",
    PaymentAction: "Done",
  },
  {
    tableno: "20A",
    OrderID: "#102977",
    CustomerName: "Rahul",
    ItemStatus: "New x 2 , Cooking x 1 , Ready to serve x 2 , Served 1",
    PaymentStatus: "In Progress",
    PaymentAction: "Done",
  },
  {
    tableno: "20A",
    OrderID: "#102977",
    CustomerName: "Rahul",
    ItemStatus: "New x 2 , Cooking x 1 , Ready to serve x 2 , Served 1",
    PaymentStatus: "In Progress",
    PaymentAction: "Done",
  },
];
